name: my_custom_env_name  # You can use any name you want here
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.3
  - pandas
  - scikit-learn=1.3.0
  - pip:
      - streamlit==1.27.2
      - lightgbm==3.3.3
